/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumPatientGender } from "./EnumPatientGender";
import { AppointmentCreateNestedManyWithoutPatientsInput } from "./AppointmentCreateNestedManyWithoutPatientsInput";
import { MedicalRecordCreateNestedManyWithoutPatientsInput } from "./MedicalRecordCreateNestedManyWithoutPatientsInput";

@InputType()
class PatientCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumPatientGender,
  })
  @IsEnum(EnumPatientGender)
  @IsOptional()
  @Field(() => EnumPatientGender, {
    nullable: true,
  })
  gender?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => AppointmentCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  appointments?: AppointmentCreateNestedManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: () => MedicalRecordCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => MedicalRecordCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => MedicalRecordCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  medicalRecords?: MedicalRecordCreateNestedManyWithoutPatientsInput;
}

export { PatientCreateInput as PatientCreateInput };
